### SHOW ALL USER
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZobyIsImVtYWlsIjoicmFmaG9AZ21haWwuY29tIiwiaWF0IjoxNjg5MjIyNzk1LCJleHAiOjE2ODkyMjI4MTV9.DDzNXjTFKT04-TENcK-gfiDtD6_df4MZh75C5YFnw0Y

### CREATE USER
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "ErdeftNew3",
    "email": "erdeft3@gmail.com",
    "password": "@Rafho123",
    "confPassword": "@Rafho123"
}

### REFRESH TOKEN
GET http://localhost:8000/token

### LOGIN
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "rafho@gmail.com",
    "password": "12345"
}

### LOGOUT
DELETE http://localhost:8000/logout

### SHOW PRODUCTS
GET http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZobyIsImVtYWlsIjoicmFmaG9AZ21haWwuY29tIiwiaWF0IjoxNjg5MjIyODM1LCJleHAiOjE2ODkyMjI4NTV9.bps2RZOATffeFb0jmjGF2wYZgqMFFpDHRnPJfSGdX1M

### SHOW PRODUCTS PAGINATION
GET http://localhost:8000/products/paging?search=&page=1&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZobyIsImVtYWlsIjoicmFmaG9AZ21haWwuY29tIiwiaWF0IjoxNjg5ODg1ODk5LCJleHAiOjE2ODk4ODU5MTl9.yiuMVfHiCom6dP2cJOWrHsIesoS9SnA6kPxzji1rqE4